DROP TABLE IF EXISTS candidato;
CREATE TABLE candidato(
   datageracao                 DATE 
  ,horageracao                 VARCHAR(8)
  ,anoeleicao                  INTEGER 
  ,tipoeleicao_id              INTEGER 
  ,tipoeleicaonome             VARCHAR(40)
  ,numeroturno                 BIT 
  ,codigoeleicao               INTEGER 
  ,descricaoeleicao            VARCHAR(100) 
  ,dataeleicao                 DATE 
  ,tipoabrangencia             VARCHAR(40)
  ,siglauf                     VARCHAR(20)
  ,unidadeeleitoral            INTEGER 
  ,nomeunidadeeleitoral        VARCHAR(80)
  ,codigocargo                 INTEGER 
  ,descricaocargo              VARCHAR(60)
  ,candidato_id                BIGINT  NOT NULL PRIMARY KEY 
  ,numerocandidato             INTEGER 
  ,nomecandidato               VARCHAR(80)
  ,nomeurnacandidato           VARCHAR(60)
  ,nomesocialcandidato         VARCHAR(80)
  ,cpfcandidato                VARCHAR(11) 
  ,emailcandidato              VARCHAR(60)
  ,codigosituacao              INTEGER 
  ,descricaosituacao           VARCHAR(40)
  ,codigodetalhesituacao       INTEGER 
  ,descricaodetalhesituacao    VARCHAR(40)
  ,tipoagremiacao              VARCHAR(40)
  ,numeropartido               INTEGER 
  ,siglapartido                VARCHAR(20)
  ,nomepartido                 VARCHAR(60)
  ,colicagao_id                BIGINT 
  ,nomecoligacao               VARCHAR(200)
  ,descricaocoligacao          VARCHAR(200)
  ,codigonacionalidade         INTEGER 
  ,descricaonacionalidade      VARCHAR(40)
  ,siglaufnascimento           VARCHAR(20)
  ,codigomunicipionascimento   INTEGER 
  ,nomemunicipionascimento     VARCHAR(60)
  ,datanascimento              DATE 
  ,idadedataposse              INTEGER 
  ,numerotitulo                VARCHAR(15) 
  ,codigogenero                INTEGER 
  ,descricaogenero             VARCHAR(40)
  ,codigograuinstrucao         INTEGER 
  ,descricaograuinstrucao      VARCHAR(40)
  ,codigoestadocivil           INTEGER 
  ,descricaoestadocivil        VARCHAR(40)
  ,codigocorraca               INTEGER 
  ,descricaocorraca            VARCHAR(40)
  ,codigoocupacao              INTEGER 
  ,descricaoocupacao           VARCHAR(80)
  ,valordespesamaximacampanha  INTEGER 
  ,codigosituacaototalturno    INTEGER 
  ,descricaosituacaototalturno VARCHAR(40)
  ,statusreeleicao             VARCHAR(1)
  ,statusdesclarabens          VARCHAR(1)
  ,numeroprotocolocandidatura  VARCHAR(40) 
  ,numeroprocesso              VARCHAR(40) 
  ,codigosituacaopleito        INTEGER 
  ,descricaosituacaopleito     VARCHAR(40)
  ,codigosituacaourna          INTEGER 
  ,descricaosituacaourna       VARCHAR(40)
  ,statusinclusaourna          VARCHAR(3)
);